import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          fontFamily: inter,
          fontSize: "1.5rem",
          fontWeight: 500,
          color: "red",
        }}
      >
        te3st dic
      </Box>
    </>
  );
}
